language: php
php:
  - hhvm
  - 5.5
  - 5.4
  - 5.3
before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
script:
  - php vendor/bin/phpunit
after_script:
  - php vendor/bin/coveralls
